"""empty message

Revision ID: ac3eafc20f63
Revises: 323cf1e1f552
Create Date: 2023-05-02 11:45:20.085851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3eafc20f63'
down_revision = '323cf1e1f552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('videogame_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('publication_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_videogame_id_video_games'), 'video_games', ['videogame_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_publication_id_publications'), 'publications', ['publication_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_publication_id_publications'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_videogame_id_video_games'), type_='foreignkey')
        batch_op.drop_column('publication_id')
        batch_op.drop_column('videogame_id')

    # ### end Alembic commands ###
